name: Publish release

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Release build
        run: ./gradlew lib:assembleRelease

      - name: Publish to MavenCentral
        run: ./gradlew lib:publishReleasePublicationToSonatypeRepository --max-workers 1 lib:closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
